# Generated by Django 5.0.4 on 2024-04-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
