version: '3.8'

services:
  web:
    restart: unless-stopped
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --no-input --clear && gunicorn GalleryStoreBackend.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - ./GalleryStoreBackend/.env:/app/GalleryStoreBackend/.env
      - sqlite_data:/app/db
      - static-volume:/app/staticfiles
    ports:
      - "8000:8000"

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/app/staticfiles
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  sqlite_data:
  static-volume:
